"""
Install a wheel / install a conda.
"""

from __future__ import annotations

import base64
import logging
import os
import subprocess
import tarfile
import tempfile
from pathlib import Path
from typing import TYPE_CHECKING, BinaryIO
from unittest.mock import patch

from conda.cli.main import main_subshell
from conda.core.package_cache_data import PackageCacheData
from installer import install
from installer.destinations import SchemeDictionaryDestination
from installer.records import Hash, RecordEntry
from installer.sources import WheelFile
from installer.utils import Scheme, copyfileobj_with_hashing

from conda_pypi.conda_build_utils import PathType

if TYPE_CHECKING:
    from tarfile import TarFile

log = logging.getLogger(__name__)


class _CondaWheelDestination(SchemeDictionaryDestination):
    """Suppress entry-point script generation.

    Conda creates entry-point scripts at install time from info/link.json
    (CEP-34), so writing them here would only embed a hardcoded shebang
    that breaks in other environments.
    """

    conda_builder: TarFile

    def __init__(self, *args, conda_builder: TarFile, **kwargs):
        super().__init__(*args, **kwargs)
        self.conda_builder = conda_builder
        self.package_paths: list[dict] = []
        self._members: set[str] = set()

    def write_script(self, name, module, attr, section):
        log.debug(f"Skipping script generation for {name} (handled via link.json)")
        return RecordEntry(path=name, hash_=None, size=None)

    def finalize_installation(self, scheme, record_file_path, records):
        # Skip RECORD file writing - conda uses paths.json instead
        pass

    def write_to_fs(
        self,
        scheme: Scheme,
        path: str,
        stream: BinaryIO,
        is_executable: bool,
    ) -> RecordEntry:
        archive_path = os.path.join(self.scheme_dict[scheme], path)
        archive_path = archive_path.replace(os.sep, "/")

        if ".." in archive_path.split("/"):
            raise ValueError(f"Path traversal detected: {archive_path}")

        if archive_path in self._members:
            if not self.overwrite_existing:
                message = f"File already exists: {archive_path}"
                raise FileExistsError(message)
            # Skip duplicate - already written to tar
            return RecordEntry(path, None, None)
        self._members.add(archive_path)

        tar_info = tarfile.TarInfo(name=archive_path)
        tar_info.mode = 0o775 if is_executable else 0o664

        with tempfile.SpooledTemporaryFile() as buffer:
            hash_, size = copyfileobj_with_hashing(stream, buffer, self.hash_algorithm)
            # hash_ is urlsafe-b64encode without padding
            pad = "=" * (-len(hash_) % 4)
            hash_hex = base64.urlsafe_b64decode(hash_ + pad).hex()
            tar_info.size = size
            buffer.seek(0)
            self.conda_builder.addfile(tar_info, buffer)

        self.package_paths.append(
            {
                "_path": archive_path,
                "path_type": str(PathType.hardlink),
                "sha256": hash_hex,
                "size_in_bytes": size,
            }
        )

        return RecordEntry(path, Hash(self.hash_algorithm, hash_), size)


def install_installer_to_tar(
    python_executable: str,
    whl: Path,
    tar: TarFile,
) -> list[dict]:
    scheme = {
        "purelib": "site-packages",
        "platlib": "site-packages",
        "scripts": "bin",
        "data": "",
        "headers": "include",
    }

    destination = _CondaWheelDestination(
        scheme_dict=scheme,
        interpreter=str(python_executable),
        script_kind="posix",
        overwrite_existing=True,
        conda_builder=tar,
    )

    with WheelFile.open(whl) as source:
        install(
            source=source,
            destination=destination,
            # Additional metadata that is generated by the installation tool.
            additional_metadata={
                "INSTALLER": b"conda-pypi",
            },
        )

    return destination.package_paths


def install_pip(python_executable: str, whl: Path, build_path: Path):
    command = [
        python_executable,
        "-m",
        "pip",
        "install",
        "--quiet",
        "--no-deps",
        "--target",
        str(build_path / "site-packages"),
        whl,
    ]
    subprocess.run(command, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    log.debug(f"Installed to {build_path}")


def install_ephemeral_conda(prefix: Path, package: Path):
    """
    Install [editable] conda package without adding it to the environment's
    package cache, since we don't want to accidentally re-install "a link to a
    source checkout" elsewhere.

    Installing packages directly from a file does not resolve dependencies.
    Should we automatically install the project's dependencies also?
    """
    persistent_pkgs = PackageCacheData.first_writable().pkgs_dir
    with (
        tempfile.TemporaryDirectory(dir=persistent_pkgs, prefix="ephemeral") as cache_dir,
        patch.dict(os.environ, {"CONDA_PKGS_DIRS": cache_dir}),
    ):
        main_subshell("install", "--prefix", str(prefix), str(package))
