"""
Install a wheel / install a conda.
"""

from __future__ import annotations

import hashlib
import logging
import os
import subprocess
import tarfile
import tempfile
from pathlib import Path
from typing import TYPE_CHECKING, BinaryIO
from unittest.mock import patch

from conda.cli.main import main_subshell
from conda.core.package_cache_data import PackageCacheData
from installer import install
from installer.destinations import SchemeDictionaryDestination
from installer.records import Hash, RecordEntry
from installer.sources import WheelFile
from installer.utils import Scheme, copyfileobj_with_hashing

from conda_pypi.conda_build_utils import PathType

if TYPE_CHECKING:
    from tarfile import TarFile

log = logging.getLogger(__name__)


class _CondaWheelDestination(SchemeDictionaryDestination):
    """Suppress entry-point script generation.

    Conda creates entry-point scripts at install time from info/link.json
    (CEP-34), so writing them here would only embed a hardcoded shebang
    that breaks in other environments.
    """

    conda_builder: TarFile

    def __init__(self, *args, conda_builder: TarFile, **kwargs):
        super().__init__(*args, **kwargs)
        self.conda_builder = conda_builder
        self.package_paths: list[dict] = []

    def write_script(self, name, module, attr, section):
        log.debug(f"Skipping script generation for {name} (handled via link.json)")
        return RecordEntry(path=name, hash_=None, size=None)

    def write_to_fs(
        self,
        scheme: Scheme,
        path: str,
        stream: BinaryIO,
        is_executable: bool,
    ) -> RecordEntry:
        target_path = os.fspath(self._path_with_destdir(scheme, path))
        archive_path = target_path.lstrip("/\\").replace(os.sep, "/")

        try:
            self.conda_builder.getmember(archive_path)
        except KeyError:
            pass
        else:
            message = f"File already exists: {target_path}"
            raise FileExistsError(message)

        tar_info = tarfile.TarInfo(name=archive_path)
        tar_info.mode = 0o775 if is_executable else 0o664

        with tempfile.SpooledTemporaryFile() as buffer:
            hash_, size = copyfileobj_with_hashing(stream, buffer, self.hash_algorithm)
            buffer.seek(0)
            hash_hex = hashlib.new(self.hash_algorithm, buffer.read()).hexdigest()
            buffer.seek(0)

            tar_info.size = size
            self.conda_builder.addfile(tar_info, buffer)

        self.package_paths.append(
            {
                "_path": archive_path,
                "path_type": str(PathType.hardlink),
                "sha256": hash_hex,
                "size_in_bytes": size,
            }
        )

        return RecordEntry(path, Hash(self.hash_algorithm, hash_), size)


def install_installer(
    python_executable: str,
    whl: Path,
    build_path: Path,
):
    # Handler for installation directories and writing into them.
    # Create site-packages directory if it doesn't exist
    site_packages = build_path / "site-packages"
    site_packages.mkdir(parents=True, exist_ok=True)

    # Scheme keys are defined by PEP 427 (the wheel format spec) and must match
    # what the installer library extracts from .data/ subdirectory names.
    # https://packaging.python.org/en/latest/specifications/binary-distribution-format/
    scheme = {
        "purelib": str(site_packages),  # Pure Python packages
        "platlib": str(site_packages),  # Platform-specific packages
        "scripts": str(build_path / "bin"),  # Console scripts
        "data": str(build_path),  # Data files (JS, CSS, templates, etc.)
        "headers": str(build_path / "include"),  # C/C++ headers (PEP 427 .data/headers/)
    }

    destination = SchemeDictionaryDestination(
        scheme_dict=scheme,
        interpreter=str(python_executable),
        script_kind="posix",
        overwrite_existing=True,
    )

    with WheelFile.open(whl) as source:
        install(
            source=source,
            destination=destination,
            # Additional metadata that is generated by the installation tool.
            additional_metadata={
                "INSTALLER": b"conda-pypi",
            },
        )

    log.debug(f"Installed to {build_path}")


def install_installer_to_tar(
    python_executable: str,
    whl: Path,
    tar: TarFile,
) -> list[dict]:
    scheme = {
        "purelib": "site-packages",
        "platlib": "site-packages",
        "scripts": "bin",
        "data": "",
        "headers": "include",
    }

    destination = _CondaWheelDestination(
        scheme_dict=scheme,
        interpreter=str(python_executable),
        script_kind="posix",
        overwrite_existing=True,
        conda_builder=tar,
    )

    with WheelFile.open(whl) as source:
        install(
            source=source,
            destination=destination,
            # Additional metadata that is generated by the installation tool.
            additional_metadata={
                "INSTALLER": b"conda-pypi",
            },
        )

    return destination.package_paths


def install_pip(python_executable: str, whl: Path, build_path: Path):
    command = [
        python_executable,
        "-m",
        "pip",
        "install",
        "--quiet",
        "--no-deps",
        "--target",
        str(build_path / "site-packages"),
        whl,
    ]
    subprocess.run(command, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    log.debug(f"Installed to {build_path}")


def install_ephemeral_conda(prefix: Path, package: Path):
    """
    Install [editable] conda package without adding it to the environment's
    package cache, since we don't want to accidentally re-install "a link to a
    source checkout" elsewhere.

    Installing packages directly from a file does not resolve dependencies.
    Should we automatically install the project's dependencies also?
    """
    persistent_pkgs = PackageCacheData.first_writable().pkgs_dir
    with (
        tempfile.TemporaryDirectory(dir=persistent_pkgs, prefix="ephemeral") as cache_dir,
        patch.dict(os.environ, {"CONDA_PKGS_DIRS": cache_dir}),
    ):
        main_subshell("install", "--prefix", str(prefix), str(package))
